openapi: "3.0.0"
info:
  version: 1.0.0
  title: open-chat
servers:
  - url: http://0.0.0.0:3000/v1
paths:
  /users/hash:
    get:
      summary: get hash
      operationId: get_users_hash
      tags:
        - users
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                required:
                  - hash
                properties:
                  hash:
                    type: string
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /rooms:
    get:
      summary: get rooms
      operationId: get_rooms
      tags:
        - rooms
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Room"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Room:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
        name:
          type: string
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
