version: '3'
services:
  db:
    image: postgres:9.6.17
    volumes:
      - .tmp/db:/var/lib/postgresql/data
    environment: 
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "5432:5432"
  api:
    build: .
    command: sh -c "rm -f /myapp/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
      - bundle_volume:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: "${DATABASE_HOST}"
      DATABASE_USERNAME: "${DATABASE_USERNAME}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
      DATABASE_NAME_TEST: "${DATABASE_NAME_TEST}"
      CORS_DOMAIN1: "${CORS_DOMAIN1}"
      CORS_DOMAIN2: "${CORS_DOMAIN2}"
volumes:
  bundle_volume: 
