version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2
  heroku: circleci/heroku@1.2.6

jobs:
  build:
    docker:
      - image: ukwpwrni/open-chat-api:0.0.1
      - image: circleci/postgres:9.6-alpine
        name: db
        environment:
          POSTGRES_USER: postgres
    executor: ruby/default
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Rubocop
          command: bundle exec rubocop
      - run: bundle update rake
      - run: bundle exec rake db:create RAILS_ENV=test
      - run: bundle exec rake db:schema:load
      - run:
          name: RSpec
          command: bundle exec rspec
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - run: heroku run rails db:migrate --app $HEROKU_APP_NAME
      - run:
          name: Heroku deploy
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git main
