version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: ukwpwrni/open-chat-api:0.0.1
    executor: ruby/default
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Rubocop
          command: bundle exec rubocop
